services:
  - type: web
    name: color-confident-studio
    runtime: ruby
    plan: starter
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: color-confident-studio-db
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 0
      - key: RAILS_MAX_THREADS
        value: 5
      - key: MALLOC_ARENA_MAX
        value: 2

databases:
  - name: color-confident-studio-db
    plan: free
