services:
  - type: web
    name: color-confident-demo
    runtime: ruby
    plan: starter
    buildCommand: './bin/render-build.sh'
    startCommand: './bin/render-start.sh'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: learn-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
databases:
  - name: color-confident-demo-db
    plan: basic-256mb
