services:
  - type: web
    name: color-confident-demo
    runtime: ruby
    plan: free
    buildCommand: './bin/render-build.sh'
    startCommand: './bin/render-start.sh'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: color-confident-demo-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production

databases:
  - name: color-confident-demo-db
    plan: free
